api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('v1/login/', views.Login.as_view(), name='login'),
    path('v1/tweet/', views.Tweet.as_view(), name='tweet1'),
    path('v2/tweet/', views.Tweet.as_view(), name='tweet2'),
]

project/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('twitter.urls', namespace='twitter')),
    path('api/', include('api.urls', namespace='api')),
    path('social/', include('social_django.urls', namespace='social')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.urls import path
from django.views.generic import ListView
from .models import Post
from . import views

app_name = 'twitter'

urlpatterns = [
	path('', ListView.as_view(template_name='twitter/index.html', model=Post, context_object_name='posts'), name='index'),
	path('new_post/', views.new_post, name='new_post'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='twitter:index'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('keygen/', views.keygen, name='keygen'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(max_length=20, default='guest')
    avatar = models.ImageField(upload_to='avatars', default='avatars/info.png')

    def __str__(self):
        return self.nickname

users/forms.py
from django import forms
from .models import User

class UserCreationForm(forms.ModelForm):
	password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
	password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'nickname', 'password1', 'password2')

	def clean_password2(self):
		# Check that the two password entries match
		password1 = self.cleaned_data.get("password1")
		password2 = self.cleaned_data.get("password2")
		if password1 and password2 and password1 != password2:
			raise forms.ValidationError("Passwords don't match")
		return password2

	def save(self, commit=True):
		# Save the provided password in hashed format
		user = super().save(commit=False)
		user.set_password(self.cleaned_data["password1"])
		if commit:
			user.save()
		return user

class UserChangeForm(forms.ModelForm):
	access_key = forms.CharField(max_length=64, widget=forms.TextInput(attrs={'disabled': True, 'size': 90}))
	class Meta:
		model = User
		fields = ('username', 'nickname', 'email', 'avatar', 'access_key')

	def __init__(self, *args, **kwargs):
		super().__init__(*args, **kwargs)

		self.fields['access_key'].initial = self.instance.accesskey.token
		for field in self.Meta.fields:
			self.fields[field].required = False

users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from .forms import UserChangeForm, UserCreationForm
from .models import User

from api.utils import create_token

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user, backend = 'django.contrib.auth.backends.ModelBackend')
            return HttpResponseRedirect(request.POST['next'])
        else:
            print(form.errors)
            return HttpResponseRedirect(reverse('users:register'))
    else:
        form = UserCreationForm()
        return render(request, 'users/register.html', context={'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        form = UserChangeForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            form.save()
        return HttpResponseRedirect(reverse('users:profile'))
    form = UserChangeForm(instance=request.user)
    posts = request.user.post_set.all()
    return render(request, 'users/profile.html', context={'form': form, 'posts': posts})


@login_required
def keygen(request):
    if request.method != 'GET':
        return HttpResponse('please use get method')
    token = create_token(request.user)
    user = request.user
    user.accesskey.token = token
    user.accesskey.save()
    return HttpResponseRedirect(reverse('users:profile'))
    

users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
	<h1>Login</h1>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='login' />
        <input type='hidden' name='next' value="{% url 'twitter:index' %}" />
    </form>
    <p>
        <a href="{% url 'social:begin' 'google-oauth2' %}">Login with Google</a>
    </p>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ user.nickname }} profile{% endblock %}

{% block content %}
	<h1>Personal information</h1>
	<img width="50px" src="{{ user.avatar.url }}" />
	<form method='POST' enctype='multipart/form-data' style='margin-bottom: 50px'>
		{% csrf_token %}
		{{ form.as_p }}
		<a href="{% url 'users:keygen' %}">Generate access key</a>
		<input type='submit' value='edit' />
		<input type='hidden' name='next' value="{% url 'users:profile' %}" />
	</form>
	<a href="{% url 'twitter:new_post' %}">New Post</a>
	<ul>
		{% for post in posts %}
			<li>
				<strong>{{ post.title }}</strong> - <span style='opacity: 0.5; font-size:80%;'>{{ post.date_created }}</span>
				<div style='margin-left: 10px'>{{ post.text | linebreaks }} </div>
			</li>
		{% empty %}
			<p>You have not posted anything yet</p>
		{% endfor %}
	</ul>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Resgister{% endblock %}

{% block content %}
    <h1>Resgister</h1>
    <form method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <input type='submit' value='register' />
        <input type='hidden' name='next' value="{% url 'twitter:index' %}" />
    </form>
{% endblock %}