api/urls.py
from django.urls import path
from . import views

app_name = 'api'

urlpatterns = [
    path('v1/login/', views.Login.as_view(), name='login'),
    path('v1/tweet/', views.Tweet.as_view(), name='tweet1'),
    path('v2/tweet/', views.Tweet.as_view(), name='tweet2'),
]

project/urls.py
from . import settings
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('twitter.urls', namespace='twitter')),
    path('api/', include('api.urls', namespace='api')),
    path('social/', include('social_django.urls', namespace='social')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter/urls.py
from django.urls import path
from django.views.generic import ListView
from .models import Post
from . import views

app_name = 'twitter'

urlpatterns = [
	path('', ListView.as_view(template_name='twitter/index.html', model=Post, context_object_name='posts'), name='index'),
	path('new_post/', views.new_post, name='new_post'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='twitter:index'), name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('keygen/', views.keygen, name='keygen'),
]

twitter/models.py
from django.db import models
from users.models import User

class Post(models.Model):
	title = models.CharField(max_length=32)
	text = models.CharField(max_length=140)
	author = models.ForeignKey(User, on_delete=models.CASCADE)
	date_created = models.DateTimeField(auto_now_add=True)

twitter/forms.py
from django import forms
from .models import Post

class NewPostForm(forms.ModelForm):
	text = forms.CharField(widget=forms.Textarea(attrs={'cols': 40, 'rows': 4}))
	class Meta:
		model = Post
		fields = ['title', 'text']

twitter/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import NewPostForm
from .models import Post

@login_required
def new_post(request):
	if request.method == 'POST':
		form = NewPostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.save()
			return HttpResponseRedirect(request.POST['next'])
		print(form.errors)
		return HttpResponseRedirect(reverse('twitter:new_post'))
	form = NewPostForm()
	return render(request, 'twitter/new_post.html', context={'form': form})

twitter/templates/twitter/index.html
{% extends 'base.html' %}

{% block content %}
	<h1>Latest posts</h1>
	<ul style='list-style-type: none;'>
		{% for post in posts %}
			<li>
				<div style='display: flex; align-items: center;'><img width='25px' src='{{post.author.avatar.url}}' />&nbsp;<strong>{{ post.title }}</strong>&nbsp;-&nbsp;<span style='opacity: 0.5; font-size:80%;'>by {{ post.author }} - {{ post.date_created }}</span></div>
				<div style='margin-left: 10px'>{{ post.text | linebreaks }}</div>
			</li>
		{% empty %}
			<p>There are no posts to show</p>
		{% endfor %}
	</ul>
{% endblock %}

twitter/templates/twitter/new_post.html
{% extends 'base.html' %}

{% block title %}New Post{% endblock %}

{% block content %}
	<h1>New Post</h1>
	<form method='POST'>
		{% csrf_token %}
		{{ form.as_p }}
		<input type='submit' value='Post' />
		<input type='hidden' name='next' value="{% url 'users:profile' %}" />
	</form>
{% endblock %}